### ISSUE TITLE
Problem compiling ffmpeg-iOS

### ISSUE THREAD

**Issue by snofla** [chrisballinger/FFmpeg-iOS-Encoder#2]
I get these errors building ffmpeg-iOS:

vp8/common/x86/subpixel_mmx.asm:233: error: beroset-p-637-invalid effective address
vp8/common/x86/subpixel_mmx.asm:389: error: beroset-p-637-invalid effective address
vp8/common/x86/subpixel_mmx.asm:544: error: beroset-p-637-invalid effective address

and then the build for libvpx fails.

Any idea how to fix this? (Do I need VP/WebM?)

**Comment by chrisballinger** [comment]
Just modify the build script to not include libvpx, I think
